# Generated by Django 2.2.7 on 2019-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeset_id', models.PositiveIntegerField(unique=True)),
                ('changeset_meta', models.TextField()),
                ('changeset_data', models.TextField()),
                ('status', models.CharField(choices=[('not_processed', 'Not Processed'), ('processed', 'Processed')], default='not_processed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push_conflicts'), ('pushed_upstream', 'Pushed_upstream')], default='not_triggered', max_length=20)),
                ('current_state_completed', models.BooleanField(default=False)),
                ('errorred', models.BooleanField(default=False)),
            ],
        ),
    ]
