# Generated by Django 2.2.8 on 2019-12-17 09:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeset_id', models.PositiveIntegerField(unique=True)),
                ('changeset_meta', models.TextField()),
                ('changeset_data', models.TextField()),
                ('status', models.CharField(choices=[('not_processed', 'Not Processed'), ('processed', 'Processed')], default='not_processed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('detecting_conflicts', 'Detecting Conflicts'), ('creating_geojsons', 'Creating GeoJSONs'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=100)),
                ('is_current_state_complete', models.BooleanField(default=False)),
                ('has_errored', models.BooleanField(default=False)),
                ('elements_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ConflictingOSMElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=15)),
                ('local_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('local_geojson', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('upstream_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('upstream_geojson', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resolved_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('local_action', models.CharField(choices=[('added', 'Added'), ('deleted', 'Deleted'), ('modified', 'Modified')], default='modified', max_length=15)),
            ],
            options={
                'unique_together': {('element_id', 'type')},
            },
        ),
    ]
