# Generated by Django 2.2.7 on 2019-12-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaytool',
            name='status',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('filtering_referenced_osm_elements', 'Filtering referenced osm elements'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push_conflicts'), ('pushed_upstream', 'Pushed_upstream')], default='not_triggered', max_length=20),
        ),
    ]
