# Generated by Django 2.2.8 on 2019-12-20 06:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0002_auto_20191218_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictingosmelement',
            name='original_geojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
