# Generated by Django 2.2.7 on 2019-12-02 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0002_auto_20191201_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('aoi_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resolved_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('node_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictingRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('aoi_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resolved_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('relation_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConflictingWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('aoi_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resolved_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('way_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='replaytool',
            name='status',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('filtering_referenced_osm_elements', 'Filtering referenced osm elements'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=20),
        ),
    ]
