# Generated by Django 2.2.8 on 2019-12-22 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0003_conflictingosmelement_original_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=15)),
                ('original_geojson', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('local_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('local_geojson', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('upstream_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('upstream_geojson', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resolved_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(default=True)),
                ('local_state', models.CharField(choices=[('added', 'Added'), ('deleted', 'Deleted'), ('modified', 'Modified'), ('conflicting', 'Conflicting')], max_length=15)),
            ],
            options={
                'unique_together': {('element_id', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='ConflictingOSMElement',
        ),
    ]
