# Generated by Django 2.2.8 on 2019-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0003_auto_20191202_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictingnode',
            name='local_action',
            field=models.CharField(choices=[('added', 'Added'), ('deleted', 'Deleted'), ('modified', 'Modified')], default='modified', max_length=15),
        ),
        migrations.AddField(
            model_name='conflictingrelation',
            name='local_action',
            field=models.CharField(choices=[('added', 'Added'), ('deleted', 'Deleted'), ('modified', 'Modified')], default='modified', max_length=15),
        ),
        migrations.AddField(
            model_name='conflictingway',
            name='local_action',
            field=models.CharField(choices=[('added', 'Added'), ('deleted', 'Deleted'), ('modified', 'Modified')], default='modified', max_length=15),
        ),
    ]
