# Generated by Django 2.2.8 on 2019-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0004_auto_20191204_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaytool',
            name='status',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('filtering_referenced_osm_elements', 'Filtering referenced osm elements'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=100),
        ),
    ]
