# Generated by Django 2.2.8 on 2020-01-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0004_auto_20191222_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='reffered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_elements', to='replay_tool.OSMElement'),
        ),
        migrations.AddField(
            model_name='osmelement',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('partially_resolved', 'Partially Resolved'), ('unresolved', 'Unresolved')], default='conflicting', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replaytool',
            name='state',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('detecting_conflicts', 'Detecting Conflicts'), ('creating_geojsons', 'Creating GeoJSONs'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('pushing_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=100),
        ),
    ]
