# Generated by Django 2.2.8 on 2020-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0005_auto_20200101_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='resolved_from',
            field=models.CharField(blank=True, choices=[('theirs', 'Theirs'), ('ours', 'Ours'), ('custom', 'Custom')], max_length=25, null=True),
        ),
    ]
