# Generated by Django 2.2.8 on 2019-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0005_auto_20191204_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replaytool',
            old_name='current_state_completed',
            new_name='has_errored',
        ),
        migrations.RenameField(
            model_name='replaytool',
            old_name='errorred',
            new_name='is_current_state_complete',
        ),
        migrations.RemoveField(
            model_name='replaytool',
            name='status',
        ),
        migrations.AddField(
            model_name='replaytool',
            name='state',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('detecting_conflicts', 'Detecting Conflicts'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=100),
        ),
    ]
