# Generated by Django 2.2.8 on 2020-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0006_osmelement_resolved_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeset_id', models.BigIntegerField(unique=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
