# Generated by Django 2.2.8 on 2019-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0006_auto_20191204_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictingnode',
            name='node_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='conflictingrelation',
            name='relation_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='conflictingway',
            name='way_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
