# Generated by Django 2.2.8 on 2020-01-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0007_upstreamchangeset'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytool',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
