# Generated by Django 2.2.8 on 2019-12-15 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0007_auto_20191205_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conflictingnode',
            old_name='aoi_data',
            new_name='upstream_data',
        ),
        migrations.RenameField(
            model_name='conflictingrelation',
            old_name='aoi_data',
            new_name='upstream_data',
        ),
        migrations.RenameField(
            model_name='conflictingway',
            old_name='aoi_data',
            new_name='upstream_data',
        ),
        migrations.AddField(
            model_name='replaytool',
            name='elements_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
