# Generated by Django 2.2.12 on 2020-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0008_replaytool_error_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayToolConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_base_url', models.CharField(default='http://172.16.1.1:81', help_text="Enter POSM's schema://IP:port that's serving osm.", max_length=100)),
                ('posm_db_host', models.CharField(default='172.16.1.1', help_text="POSM's IP which listens to psql connections.", max_length=100)),
                ('posm_db_name', models.CharField(default='osm', help_text='OSM Database Name', max_length=100)),
                ('posm_db_user', models.CharField(default='osm', help_text='OSM Database User', max_length=100)),
                ('posm_db_password', models.CharField(default='openstreetmap', help_text='OSM Database password', max_length=100)),
                ('aoi_root', models.CharField(default='/aoi', help_text="Path inside docker mapped with host's /opt/data/aoi", max_length=100)),
                ('aoi_name', models.CharField(default='', help_text='Directory name of AOI which contains manifest.json and other files.', max_length=100)),
                ('osmosis_db_host', models.CharField(default='172.16.1.1', help_text='This is probably the IP of POSM itself', max_length=100)),
                ('osmosis_aoi_root', models.CharField(default='/opt/data/aoi', help_text='Host AOI root location.', max_length=100)),
                ('oauth_consumer_key', models.CharField(default='', help_text='OSM OAUTH consumer key', max_length=300)),
                ('oauth_consumer_secret', models.CharField(default='', help_text='OSM OAUTH consumer secret', max_length=300)),
                ('overpas_api_url', models.CharField(default='http://overpass-api.de/api/interpreter', help_text='Overpass api from where upstream data is pulled', max_length=100)),
                ('request_token_url', models.CharField(default='https://master.apis.dev.openstreetmap.org/oauth/request_token', help_text='OSM OAuth api endpoint for request token', max_length=300)),
                ('access_token_url', models.CharField(default='https://master.apis.dev.openstreetmap.org/oauth/access_token', help_text='OSM OAuth api endpoint for access token', max_length=300)),
                ('authorize_url', models.CharField(default='https://master.apis.dev.openstreetmap.org/oauth/authorize', help_text='OSM OAuth api endpoint for authorization', max_length=300)),
            ],
        ),
    ]
