# Generated by Django 2.2.8 on 2019-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0008_auto_20191215_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaytool',
            name='state',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('gathering_changesets', 'Gathering Changesets'), ('extracting_local_aoi', 'Extracting Local Aoi'), ('extracting_upstream_aoi', 'Extracting Upstream Aoi'), ('detecting_conflicts', 'Detecting Conflicts'), ('creating_geojsons', 'Creating GeoJSONs'), ('conflicts', 'Conflicts'), ('resolved', 'Resolved'), ('push_conflicts', 'Push Conflicts'), ('pushed_upstream', 'Pushed Upstream')], default='not_triggered', max_length=100),
        ),
    ]
