# Generated by Django 2.2.19 on 2021-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay_tool', '0010_auto_20200716_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='access_token_url',
            field=models.CharField(help_text='OSM OAuth api endpoint for access token', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='aoi_name',
            field=models.CharField(help_text='Directory name of AOI which contains manifest.json and other files.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='aoi_root',
            field=models.CharField(help_text="Path inside docker mapped with host's /opt/data/aoi", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='authorization_url',
            field=models.CharField(help_text='OSM OAuth api endpoint for authorization', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='oauth_api_url',
            field=models.CharField(help_text='OSM oauth root api endpoint', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='oauth_consumer_key',
            field=models.CharField(help_text='OSM OAUTH consumer key', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='oauth_consumer_secret',
            field=models.CharField(help_text='OSM OAUTH consumer secret', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='original_aoi_file_name',
            field=models.CharField(help_text='File name for original aoi[osm file located inside aoi along with manifest json]', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='osm_base_url',
            field=models.CharField(help_text="Enter POSM's schema://IP:port that's serving osm.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='osmosis_aoi_root',
            field=models.CharField(help_text='Host AOI root location.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='osmosis_db_host',
            field=models.CharField(help_text='This is probably the IP of POSM itself', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='overpass_api_url',
            field=models.CharField(help_text='Overpass api from where upstream data is pulled', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='posm_db_host',
            field=models.CharField(help_text="POSM's IP which listens to psql connections.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='posm_db_name',
            field=models.CharField(help_text='OSM Database Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='posm_db_password',
            field=models.CharField(help_text='OSM Database password', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='posm_db_user',
            field=models.CharField(help_text='OSM Database User', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replaytoolconfig',
            name='request_token_url',
            field=models.CharField(help_text='OSM OAuth api endpoint for request token', max_length=300, null=True),
        ),
    ]
